# POST http://localhost:4000/site/addStudent
# Content-Type: application/json

# {
#     "name": "Amna",
#     "password": "nb378",
#     "age": "30"
# }

###

# POST http://localhost:4000/site/addStudent
# Content-Type: application/json

# {
#     "name": "Salma",
#     "password": "gh353",
#     "age": "26"
# }

# ###

# GET http://localhost:4000/site/getStudent
# Accept: application/json